# docker/docker-compose.yml

services:
  db:
    image: mysql:9.2.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "5004:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
